#!/usr/bin/env bash
# scripts/install-edge-boot.sh — install the Caddy-edge boot Quadlet.
#
# Purpose      : Arm rootless-podman boot persistence for the HelixCode Caddy
#                edge so it auto-starts on host reboot / user login. Copies the
#                tracked Quadlet source of truth into the user Quadlet dir, and
#                (only if deploy/.env carries a non-empty ACME token) writes an
#                out-of-repo Quadlet drop-in with that token, then runs
#                `systemctl --user daemon-reload` so the podman generator turns
#                it into helixcode-caddy.service. The
#                [Install] WantedBy=default.target in the .container means boot
#                start is armed by daemon-reload alone — no `systemctl enable`.
#
# Usage        : scripts/install-edge-boot.sh            # install + arm boot
#                scripts/install-edge-boot.sh --start    # also start NOW
#                scripts/install-edge-boot.sh --uninstall # remove + disarm
#
#                By DEFAULT it does NOT start the container: while the compose
#                `deploy_caddy_1` is live it owns ports 52443/52080, so a start
#                would fail with a port clash. --start is guarded: it refuses to
#                start while `deploy_caddy_1` is running (§11.4.174 / no clobber).
#
# Inputs       : deploy/quadlet/helixcode-caddy.container (source of truth),
#                deploy/.env (optional, for ACME_DNS_API_TOKEN passthrough).
# Outputs      : ~/.config/containers/systemd/helixcode-caddy.container,
#                (optional) …/helixcode-caddy.container.d/10-token.conf (0600),
#                a daemon-reloaded helixcode-caddy.service.
# Side-effects : daemon-reload; with --start, starts helixcode-caddy.service.
# Dependencies : podman 5.x (Quadlet), systemd --user, linger=yes.
# Cross-refs   : deploy/quadlet/helixcode-caddy.container, docs/guides/EDGE_BOOT.md.
#
# §11.4.10 credentials: the token is NEVER echoed; a real token is written only
#          into an out-of-repo Quadlet drop-in (chmod 600) — never versioned.
# §11.4.6  no-guessing: values live in the tracked .container mirrored from the
#          live container; this script only places + arms them.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_UNIT="${REPO_ROOT}/deploy/quadlet/helixcode-caddy.container"
QUADLET_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/containers/systemd"
DEST_UNIT="${QUADLET_DIR}/helixcode-caddy.container"
# Out-of-repo Quadlet drop-in dir that MERGES OVER the tracked .container; used
# to inject a REAL ACME token without ever versioning the secret (§11.4.10).
DROPIN_DIR="${QUADLET_DIR}/helixcode-caddy.container.d"
DROPIN_TOKEN="${DROPIN_DIR}/10-token.conf"
DEPLOY_ENV="${REPO_ROOT}/deploy/.env"
SERVICE="helixcode-caddy.service"

log() { printf '[install-edge-boot] %s\n' "$*"; }
die() { printf '[install-edge-boot] ERROR: %s\n' "$*" >&2; exit 1; }

uninstall() {
  log "Disarming boot persistence for the Caddy edge…"
  systemctl --user stop "${SERVICE}" 2>/dev/null || true
  rm -f "${DEST_UNIT}" "${DROPIN_TOKEN}"
  rmdir "${DROPIN_DIR}" 2>/dev/null || true
  systemctl --user daemon-reload
  log "Removed ${DEST_UNIT} (+ token drop-in) and reloaded."
  exit 0
}

[ "${1:-}" = "--uninstall" ] && uninstall

command -v podman >/dev/null 2>&1 || die "podman not found on PATH."
[ -f "${SRC_UNIT}" ] || die "source unit missing: ${SRC_UNIT}"

# 1) Install the Quadlet unit (source of truth -> user Quadlet dir).
mkdir -p "${QUADLET_DIR}"
install -m 0644 "${SRC_UNIT}" "${DEST_UNIT}"
log "Installed ${DEST_UNIT}"

# 2) ACME token passthrough. The tracked unit ships an EMPTY token (matches the
#    live container). Only if deploy/.env carries a NON-EMPTY token do we write
#    an out-of-repo Quadlet drop-in that MERGES OVER it — never echoed, 0600,
#    never versioned (§11.4.10). Empty token => no drop-in (nothing to protect).
if [ -f "${DEPLOY_ENV}" ] && grep -Eq '^ACME_DNS_API_TOKEN=.+' "${DEPLOY_ENV}"; then
  mkdir -p "${DROPIN_DIR}"; chmod 700 "${DROPIN_DIR}"
  v="$(grep -E '^ACME_DNS_API_TOKEN=' "${DEPLOY_ENV}" | tail -n1)"
  umask 177
  { printf '# Auto-generated by install-edge-boot.sh — ACME token (§11.4.10, never versioned).\n'
    printf '[Container]\n%s\n' "${v}"; } > "${DROPIN_TOKEN}"
  chmod 600 "${DROPIN_TOKEN}"
  log "Wrote token drop-in ${DROPIN_TOKEN} (0600) — value NOT echoed."
else
  rm -f "${DROPIN_TOKEN}" 2>/dev/null || true
  log "ACME token empty/absent in deploy/.env — using the unit's empty default (matches live)."
fi

# 3) daemon-reload => podman generator arms boot start via [Install] WantedBy.
systemctl --user daemon-reload
log "daemon-reload done — ${SERVICE} is armed to start on login/boot."

# 4) Optionally start now, but never clobber the live compose container.
if [ "${1:-}" = "--start" ]; then
  if podman ps --format '{{.Names}}' 2>/dev/null | grep -qx 'deploy_caddy_1'; then
    die "deploy_caddy_1 is RUNNING (owns 52443/52080). Stop it first, then: systemctl --user start ${SERVICE}"
  fi
  systemctl --user start "${SERVICE}"
  log "Started ${SERVICE}."
  systemctl --user --no-pager status "${SERVICE}" | head -n 10 || true
else
  log "Not started (default). It will start automatically on next boot/login."
  log "To activate NOW (only after the compose edge is stopped): systemctl --user start ${SERVICE}"
fi
