#!/usr/bin/env bash
# scripts/setup.sh — interactive setup wizard for HelixCode (CLI + TUI).
#
# Purpose:      Collect the deployment configuration (login password, projects
#               to expose, port prefix) and write deploy/.env (chmod 600).
# Usage:        scripts/setup.sh            # CLI prompts (default)
#               scripts/setup.sh --tui      # whiptail TUI if available, else CLI
#               scripts/setup.sh --non-interactive  # use env/defaults, no prompts
# Inputs:       interactive answers, or env vars CODE_SERVER_PASSWORD / PROJECTS /
#               PORT_PREFIX (used as defaults / in --non-interactive mode)
# Outputs:      deploy/.env (mode 600), never committed (git-ignored)
# Side-effects: writes deploy/.env; creates deploy/ if missing
# Dependencies: bash; optional: whiptail (for --tui)
# Cross-references: docs/scripts/README.md, deploy/.env.example, scripts/start.sh
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

MODE="cli"
case "${1:-}" in
	--tui) MODE="tui" ;;
	--non-interactive) MODE="batch" ;;
	-h|--help) sed -n '2,12p' "${BASH_SOURCE[0]}"; exit 0 ;;
	"") ;;
	*) hc_err "unknown arg: $1"; exit 2 ;;
esac

mkdir -p "$HC_DEPLOY"
# Defaults (env overrides, then prior .env, then hardcoded)
hc_load_env 2>/dev/null || true
DEF_PREFIX="${PORT_PREFIX:-52}"
DEF_PROJECTS="${PROJECTS:-}"
DEF_PASSWORD="${CODE_SERVER_PASSWORD:-}"

ask_cli() {
	local prefix projects password password2
	read -r -p "Port prefix [${DEF_PREFIX}]: " prefix; prefix="${prefix:-$DEF_PREFIX}"
	read -r -p "Projects to expose (colon-separated abs paths) [${DEF_PROJECTS}]: " projects; projects="${projects:-$DEF_PROJECTS}"
	while :; do
		read -r -s -p "Login password: " password; echo
		read -r -s -p "Confirm password: " password2; echo
		[ -n "$password" ] && [ "$password" = "$password2" ] && break
		hc_warn "passwords empty or do not match — try again"
	done
	PREFIX="$prefix"; PROJECTS_V="$projects"; PASSWORD_V="$password"
}

ask_tui() {
	command -v whiptail >/dev/null 2>&1 || { hc_warn "whiptail not installed; falling back to CLI"; ask_cli; return; }
	PREFIX="$(whiptail --inputbox "Port prefix (exposed ports = PREFIX000-PREFIX999)" 10 60 "$DEF_PREFIX" 3>&1 1>&2 2>&3)" || exit 1
	PROJECTS_V="$(whiptail --inputbox "Projects to expose (colon-separated absolute paths)" 10 70 "$DEF_PROJECTS" 3>&1 1>&2 2>&3)" || exit 1
	PASSWORD_V="$(whiptail --passwordbox "Login password" 10 60 "" 3>&1 1>&2 2>&3)" || exit 1
	[ -n "$PASSWORD_V" ] || { hc_err "password must not be empty"; exit 1; }
}

case "$MODE" in
	cli)   ask_cli ;;
	tui)   ask_tui ;;
	batch) PREFIX="$DEF_PREFIX"; PROJECTS_V="$DEF_PROJECTS"; PASSWORD_V="$DEF_PASSWORD"
	       [ -n "$PASSWORD_V" ] || { hc_err "--non-interactive needs CODE_SERVER_PASSWORD in env"; exit 2; } ;;
esac

# Validate prefix keeps every exposed port <= 65535 (PREFIX*1000+999).
if ! [[ "$PREFIX" =~ ^[0-9]+$ ]] || [ $((PREFIX*1000+999)) -gt 65535 ]; then
	hc_err "port prefix '$PREFIX' invalid (PREFIX*1000+999 must be <= 65535; e.g. 52)"; exit 2
fi

umask 077
cat > "$HC_DEPLOY/.env" <<ENV
# HelixCode deploy config — generated by scripts/setup.sh. NOT committed.
PORT_PREFIX=$PREFIX
CODE_SERVER_PASSWORD=$PASSWORD_V
PROJECTS=$PROJECTS_V
ENV
chmod 600 "$HC_DEPLOY/.env"
hc_info "wrote $HC_DEPLOY/.env (mode 600)"
hc_info "exposed: https on ${PREFIX}443, http on ${PREFIX}080"
hc_info "next: scripts/start.sh   (or scripts/install.sh for a full, reboot-persistent install)"
hc_info "change the password later with: scripts/set-password.sh"
